#! /usr/bin/expect

set ubr_addr "[lindex $argv 0]"
set user "[lindex $argv 1]"
set pass "[lindex $argv 2]"
#set enable "[lindex $argv 3]"
#set cmd "[lrange $argv 3 end]"
set cmd "[lindex $argv 3]"

spawn /usr/bin/telnet $ubr_addr telnet

expect {
        -regex "^.*ogin:" { send "$user\r" }
        timeout close
}
expect {
        -regex "^.*assword:" { send "$pass\r" }
        timeout close
}

expect {
	-regex "^.*>" {
			send "enable\r"
			timeout close
			expect {
				-regex "^.*assword:" { send "$pass\r" }
				timeout close
			}
			expect {
				-regex "^.*#" { send "page off\r" }
			}
			expect {
				-regex "^.*#" {
						send_user " (BEGIN COMMAND OUTPUT) "; # print to output but not to CMTS
						send "$cmd\r" ;
					}
			}
			expect {
				-regex "^.*#" {
						send_user " (END COMMAND OUTPUT) "; # print to output but not to CMTS
						send "exit\r";
					}
				timeout close
			}
		}
	-regex "^.*#" {
			send "page off\r"
			expect {
				-regex "^.*#" {
						send_user " (BEGIN COMMAND OUTPUT) "; # print to output but not to CMTS
						send "$cmd\r" ;
					}
			}
			expect {
				-regex "^.*#" {
						send_user " (END COMMAND OUTPUT) "; # print to output but not to CMTS
						send "exit\r";
					}
				timeout close
			}
		}
	timeout close
}

expect eof

